version: '3'
services:
  backend:
    image: loc05st/nestjs_blog:latest
    container_name: nestjs_blog_backend
    build: ./
    ports:
      - 3000:3000
  db:
    image: mysql:8.0.22
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: nestjs_blog
      MYSQL_ROOT_PASSWORD: 1234567890
    volumes:
      - ./data/mysql:/var/lib/mysql
